title: Métodos de análisis cuantitativos multivariados
subtitle: Track de Métodos Cuantitativos y Ciencias Sociales Computacionales
description: Materiales del curso       
show_downloads: true
theme: jekyll-theme-cayman
site.url: https://gefero.github.io/factor_data_track_CSS/
