title: Track de Métodos Cuantitativos y Ciencias Sociales Computacionales
subtitle: Presentación - acceso a módulos y materiales
description: Acceso a contenidos  
show_downloads: false
theme: jekyll-theme-cayman
site.url: https://gefero.github.io/factor_data_track_CSS/
