title: Procesamiento de datos en R y estadística para Ciencias Sociales
subtitle: Track de Métodos Cuantitativos y Ciencias Sociales Computacionales
description: Materiales del curso       
show_downloads: true
